Algoritmo "turnos"

Var
turno : caracter

Inicio
escreval (" Digite o turno que você estuda")
escreval (" Digite M para Matutino")
escreval (" Digite V para Vespertino")
escreval (" Digite N para Noturno")
leia (turno)

se turno ="M" entao
	escreval (" Bom Dia!")
senao
se turno ="V" entao
	escreval (" Boa Tarde!")
senao
se turno ="N" entao
	escreval (" Boa Noite!")
senao
	escreval (" Valor Inválido!")
 fimse
 fimse
fimse
Fimalgoritmo

